"""Shared scheduling weights and thresholds."""

SCHEDULING_DAY_START_TIME = "09:00"
SCHEDULING_DAY_END_TIME = "18:00"

DEFAULT_SOFT_CONSTRAINT_WEIGHTS = {
    "PREFERRED_DAY_MISMATCH": 15,
    "AVOID_DAY": 30,
    "ONLINE_NOT_MON_TUE": 5,
    "SHORT_CAMPUS_DAY": 10,
    "TUTOR_IDLE_GAP": 25,
    "LONG_CONSECUTIVE_DAY": 20,
    "ONLINE_F2F_ADJACENT_SWITCH": 15,
}

TUTOR_IDLE_GAP_MINUTES = 120
SHORT_CAMPUS_DAY_MAX_MINUTES = 120
LONG_CONSECUTIVE_DAY_MINUTES = 240
